[package]
name = "egui_winit"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash.workspace = true
egui.workspace = true
log.workspace = true
serde.workspace = true
winit.workspace = true

raw-window-handle = "0.6.2"
web-time = "1.1.0"
