[package]
name = "voxea_vst"
version = "0.1.0"
edition = "2021"

[dependencies]
voxea_macro.workspace = true

libc = "0.2.158"
libloading = "0.8.5"
winapi = "0.3.9"
windows-core = "0.58.0"
windows-sys = "0.59.0"
windows-implement = "0.58.0"
windows-interface = "0.58.0"