// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
package plugin

// #include "plugin.h"
// #include <stdlib.h>
import "C"
import "unsafe"
// Import functions from sdk:component/logger
func SdkComponentLoggerLog(text string) {
  var lower_text C.plugin_string_t

  // use unsafe.Pointer to avoid copy
  lower_text.ptr = (*uint8)(unsafe.Pointer(C.CString(text)))
  lower_text.len = C.size_t(len(text))
  C.sdk_component_logger_log(&lower_text )
}

// Import functions from sdk:component/registry
func SdkComponentRegistryGetSignal(idx uint64) float64 {
  lower_idx := C.uint64_t(idx)
  ret := C.sdk_component_registry_get_signal(lower_idx )
  var lift_ret float64
  lift_ret = float64(ret)
  return lift_ret
}

func SdkComponentRegistrySetSignal(idx uint64, val float64) float64 {
  lower_idx := C.uint64_t(idx)
  lower_val := C.double(val)
  ret := C.sdk_component_registry_set_signal(lower_idx , lower_val )
  var lift_ret float64
  lift_ret = float64(ret)
  return lift_ret
}

// Export functions from sdk:component/plugin-api
var exports_sdk_component_plugin_api ExportsSdkComponentPluginApi = nil
// `SetExportsSdkComponentPluginApi` sets the `ExportsSdkComponentPluginApi` interface implementation.
// This function will need to be called by the init() function from the guest application.
// It is expected to pass a guest implementation of the `ExportsSdkComponentPluginApi` interface.
func SetExportsSdkComponentPluginApi(i ExportsSdkComponentPluginApi) {
  exports_sdk_component_plugin_api = i
}
type ExportsSdkComponentPluginApi interface {
  Enable() int32 
  Disable() int32 
  ProcessSignal(ptr uint64) 
}
//export exports_sdk_component_plugin_api_enable
func exportsSdkComponentPluginApiEnable() C.int32_t {
  result := exports_sdk_component_plugin_api.Enable()
  lower_result := C.int32_t(result)
  return lower_result

}
//export exports_sdk_component_plugin_api_disable
func exportsSdkComponentPluginApiDisable() C.int32_t {
  result := exports_sdk_component_plugin_api.Disable()
  lower_result := C.int32_t(result)
  return lower_result

}
//export exports_sdk_component_plugin_api_process_signal
func exportsSdkComponentPluginApiProcessSignal(ptr C.uint64_t) {
  var lift_ptr uint64
  lift_ptr = uint64(ptr)
  exports_sdk_component_plugin_api.ProcessSignal(lift_ptr)

}
