// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
#include "plugin.h"
#include <stdlib.h>
#include <string.h>

// Imported Functions from `sdk:component/logger`

__attribute__((__import_module__("sdk:component/logger"), __import_name__("log")))
extern void __wasm_import_sdk_component_logger_log(uint8_t *, size_t);

// Imported Functions from `sdk:component/registry`

__attribute__((__import_module__("sdk:component/registry"), __import_name__("get-signal")))
extern double __wasm_import_sdk_component_registry_get_signal(int64_t);

__attribute__((__import_module__("sdk:component/registry"), __import_name__("set-signal")))
extern double __wasm_import_sdk_component_registry_set_signal(int64_t, double);

// Exported Functions from `sdk:component/plugin-api`




// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void plugin_string_set(plugin_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void plugin_string_dup(plugin_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void plugin_string_free(plugin_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

void sdk_component_logger_log(plugin_string_t *text) {
  __wasm_import_sdk_component_logger_log((uint8_t *) (*text).ptr, (*text).len);
}

double sdk_component_registry_get_signal(uint64_t idx) {
  double ret = __wasm_import_sdk_component_registry_get_signal((int64_t) (idx));
  return ret;
}

double sdk_component_registry_set_signal(uint64_t idx, double val) {
  double ret = __wasm_import_sdk_component_registry_set_signal((int64_t) (idx), val);
  return ret;
}

__attribute__((__export_name__("sdk:component/plugin-api#enable")))
int32_t __wasm_export_exports_sdk_component_plugin_api_enable(void) {
  int32_t ret = exports_sdk_component_plugin_api_enable();
  return ret;
}

__attribute__((__export_name__("sdk:component/plugin-api#disable")))
int32_t __wasm_export_exports_sdk_component_plugin_api_disable(void) {
  int32_t ret = exports_sdk_component_plugin_api_disable();
  return ret;
}

__attribute__((__export_name__("sdk:component/plugin-api#process-signal")))
void __wasm_export_exports_sdk_component_plugin_api_process_signal(int64_t arg) {
  exports_sdk_component_plugin_api_process_signal((uint64_t) (arg));
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_plugin(void);
void __component_type_object_force_link_plugin_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_plugin();
}
