[package]
name = "voxea_macro"
version = "0.1.0"
edition = "2021"

[dependencies]

proc-macro2 = "1.0.86"
quote = "1.0.37"
syn = { version = "2.0.77", features = ["full"] }
log = "0.4.22"

[lib]
proc-macro = true