package sdk:component;

interface logger {
    log: func(text: string);
}

interface plugin-api {
    enable: func() -> s32;
    disable: func() -> s32;

    process-signal: func(ptr: u64);
}

interface registry {
    get-signal: func(idx: u64) -> f64;
    set-signal: func(idx: u64, val: f64) -> f64;
}

world plugin {
    import logger;
    import registry;

    export plugin-api;
}