[package]
name = "voxea_audio"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
cpal.workspace = true
hound = "3.5.1"
log.workspace = true
thiserror.workspace = true
tracing-subscriber.workspace = true